{{ if .Values.opentelemetryOperator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger
  namespace: {{ template "tobs.namespace" . }}
  labels:
    app: jaeger
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "tobs.fullname" . }}
    component: jaeger
{{- if .Values.opentelemetryOperator.jaeger.service.loadBalancer.enabled }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
{{- end }}
  ports:
  - name: jaeger
    port: 16686
    targetPort: 16686
    protocol: TCP
{{- end -}}